version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
  deploy-to-stg:
    docker: 
      - image: debian:stretch
    steps:
      - run: 
         name: Deploying to staging Started
         command: ls -l
  deploy-to-prod:
    docker:
     - image: debian:stretch
    steps:
     #- checkout
     - run:
         name: Deployment to Prod Started
         command: ls -l
workflows:
 version: 2
 build-deploy:
   jobs:
    - build
    - deploy-to-stg:
       requires:
        - build
       filters:
         branches:
           only: qa
    - deploy-to-preprod:
        type: approval
        requires:
          - deploy-to-stg
        filters:
           branches:
             only: qa
    - deploy-to-prod:
       requires:
         - build
       filters:
         branches:
            only: master
