version: 2
jobs:
 build:
  docker:
   - image: circleci/ruby:2.4.2-jessie-node
   #- image: circleci/postgres:9.5-alpine
  steps:
   - checkout
   - run: 
       name: Which Bundler 
       command: bundle -v
