version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
  deploy:
    docker:
     - image: debian:stretch
    steps:
     - checkout
     - run:
         name: Deployment Started
         command: ls -l
workflows:
 version: 2
 build-deploy:
   jobs:
    - build
    - deploy:
       requires:
         - build
       filters:
         branches:
            only:master
